<<<<<<< HEAD
import Head from 'next/head'
import styles from '../styles/Home.module.css'
=======
import Banner from "../Components/Banner/Banner";
import Footer from "../Components/Footer/Footer";
import AllFrelancers from "../Components/Frelancers/AllFrelancers/AllFrelancers";
import Blogs from "../Components/HomeBlog/Blogs";
import Navbar from "../Components/Navbar/Navbar";
import PhotoCollection from "../Components/PhotoCollection/PhotoCollection";
import PhotomaneaBox from "../Components/PhotomaneaBox/PhotomaneaBox";
>>>>>>> tunvir

export default function Home() {
  return (
<<<<<<< HEAD
    <div className="main-container">
      {/* <Navbar/> */}
      <Banner/>
      <AllFrelancers/>
      <PhotomaneaBox/>
      <PhotoCollection/>
<<<<<<< HEAD
=======
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Login or, Register</h1>
      </main>

      <footer className={styles.footer}>
        
      </footer>
>>>>>>> tahrimur_rashid
=======
      <Blogs/>
      <Footer/>
>>>>>>> tunvir
    </div>
  )
}
